events {
    # The maximum number of simultaneous connections that can be opened by a worker process. This value should be set to the maximum number of clients that you expect to connect to your server at the same time. If you have a high traffic website, you may want to increase this value. However, keep in mind that increasing this value will also increase the amount of memory used by Nginx. The default value is 1024, which is usually sufficient for most websites. If you are experiencing connection issues or timeouts, you may want to consider increasing this value.
    worker_connections 1024; 
}

http {
    access_log off;
    
    upstream api {
        server localhost:8081;
        server localhost:8082;
    }

    server {
        listen 9999;
        
        location / {
            proxy_pass http://api;
        }
    }
}
